import React from 'react';
import { 
    Accordion, 
    AccordionContent, 
    AccordionItem, 
    AccordionTrigger 
} from "@/components/ui/Accordion";
import { AlertTriangle, Info } from 'lucide-react'; // Use appropriate icons

const LegalDisclaimer: React.FC = () => {
  return (
    // Use Accordion component, allow multiple open or just one with type="single"
    <Accordion type="single" collapsible className="w-full">
      <AccordionItem value="disclaimer" className="border border-border rounded-lg bg-muted/30 px-4 mb-4">
        <AccordionTrigger className="text-sm font-medium text-foreground hover:no-underline py-3">
          <div className="flex items-center">
             <AlertTriangle className="h-4 w-4 mr-2 text-primary" /> {/* Changed color to primary */}
             Important Legal Disclaimer
          </div>
        </AccordionTrigger>
        <AccordionContent className="text-sm text-muted-foreground pt-0 pb-3 space-y-2">
          <p>
            BenchWise (Alpha) is designed to assist legal professionals by providing document analysis and organization tools. It is not a substitute for professional legal advice.
          </p>
          <p>
            This application does not create an attorney-client relationship, and all content generated by the AI should be reviewed by a qualified legal professional before use.
          </p>
          <p>
            By using this application, you acknowledge that the analysis and suggestions provided are for informational purposes only and may not be accurate or complete in all circumstances.
          </p>
        </AccordionContent>
      </AccordionItem>
    </Accordion>
  );
};

export default LegalDisclaimer;