import React, { useState } from 'react';

const LegalDisclaimer: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="mb-5 rounded-xl border border-amber-600/20 bg-amber-900/10 backdrop-blur-sm transition-all duration-300 hover:bg-amber-900/20">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex w-full items-center justify-between px-5 py-4 text-left text-sm font-medium text-amber-400 transition-colors duration-300 hover:text-amber-300"
      >
        <div className="flex items-center">
          <svg 
            xmlns="http://www.w3.org/2000/svg" 
            className="h-5 w-5 mr-3 transition-all duration-300" 
            viewBox="0 0 20 20" 
            fill="currentColor"
          >
            <path 
              fillRule="evenodd" 
              d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" 
              clipRule="evenodd" 
            />
          </svg>
          Important Legal Disclaimer
        </div>
        <svg 
          xmlns="http://www.w3.org/2000/svg" 
          className={`h-5 w-5 transform transition-transform duration-300 ease-in-out ${isOpen ? 'rotate-180' : ''}`} 
          viewBox="0 0 20 20" 
          fill="currentColor"
        >
          <path 
            fillRule="evenodd" 
            d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" 
            clipRule="evenodd" 
          />
        </svg>
      </button>
      
      <div 
        className={`overflow-hidden transition-all duration-300 ease-in-out ${
          isOpen ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'
        }`}
      >
        <div className="px-5 pb-5 text-sm text-gray-400 space-y-3">
          <p>
            The Paralegal AI Assistant is designed to assist legal professionals by providing document analysis and organization tools. It is not a substitute for professional legal advice.
          </p>
          <p>
            This application does not create an attorney-client relationship, and all content generated by the AI should be reviewed by a qualified legal professional before use.
          </p>
          <p>
            By using this application, you acknowledge that the analysis and suggestions provided are for informational purposes only and may not be accurate or complete in all circumstances.
          </p>
        </div>
      </div>
    </div>
  );
};

export default LegalDisclaimer;